### PR TITLE
0.3.1 - Fix for deprecated atom calls

### PR DESCRIPTION
**Pull request by framerate**
Had some spare time!

### CODE REVIEW

**Comment by framerate** [comment]
I'm not great with Atom's flow yet, so I may have missed some. I'm having a hard time finding out if I fixed all the deprecations or not! Seems different if I'm in dev or normal mode... 2nd opinion would be great.

**Comment by framerate** [comment]
There are some more changes necessary, a bit deeper. I'm investigating.

**Comment by framerate** [comment]
Ok, fixed the others except one. Can someone @cliffrowley maybe help? Here's deprecation error:


Deprecation Cop
Here's the code:

```
fetchBuildArray: ->
      url = @repo.getOriginUrl()
```

Seems like a false positive to me?

**Comment by framerate** [comment]
Nevermind, it's done @cliffrowley! Let me know if you have any further issues with it or if you want help maintaining this package!

**Comment by tiwilliam** [comment]
Awesome, thanks!

**Comment by cliffrowley** [comment]
Good work @framerate - thanks!

I'm not in a position to test it currently, @tiwilliam let me know if you're happy and I will publish a patch version :-)

**Comment by framerate** [comment]
Thanks guys! I think I got them all. If not, lemme know!



—
-jhttp://framerate.io

**Comment by tiwilliam** [comment]
@cliffrowley I've already tested and pushed it.

**Comment by framerate** [comment]
Awesome thanks @tiwilliam!

**Comment by cliffrowley** [comment]
Fantastic, thanks - that answers that question for me!

**Pull request merged**
